version: '3.8'

services:
  db:
    image: postgres:15
    container_name: velo_db
    env_file:
      - .ENV
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: velo_pgadmin
    env_file:
      - .ENV
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  web:
    build: .
    container_name: velo_web
    env_file:
      - .ENV
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app  # ✅ Zorg voor live reload van alle projectbestanden
    command: python app.py  # ✅ Start de app handmatig zodat debug werkt

volumes:
  postgres_data:
  pgadmin_data:
