CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "voornaam" VARCHAR,
  "achternaam" VARCHAR,
  "email" VARCHAR,
  "abonnementstype" VARCHAR,
  "registratie_datum" TIMESTAMP WITHOUT TIME ZONE,
  "postcode" VARCHAR,
  "stad" VARCHAR
);

CREATE TABLE "stations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naam" VARCHAR,
  "adres" VARCHAR,
  "latitude" DECIMAL,
  "longitude" DECIMAL,
  "free_bikes" INT,
  "empty_slots" INT,
  "capaciteit" INT

);

CREATE TABLE "bikes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" VARCHAR,
  "status" VARCHAR
);

CREATE TABLE "rentals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "bike_id" INT,
  "start_station_id" INT,
  "eind_station_id" INT,
  "starttijd" TIMESTAMP WITHOUT TIME ZONE,
  "eindtijd" TIMESTAMP WITHOUT TIME ZONE,
  "prijs" DECIMAL
);

CREATE TABLE "bike_locations" (
  "bike_id" INT,
  "station_id" INT,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE,
  PRIMARY KEY ("bike_id", "timestamp")
);

CREATE TABLE "maintenance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bike_id" INT,
  "datum" TIMESTAMP WITHOUT TIME ZONE,
  "beschrijving" TEXT,
  "status" VARCHAR
);

ALTER TABLE "rentals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("start_station_id") REFERENCES "stations" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("eind_station_id") REFERENCES "stations" ("id");

ALTER TABLE "bike_locations" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
ALTER TABLE "bike_locations" ADD FOREIGN KEY ("station_id") REFERENCES "stations" ("id");

ALTER TABLE "maintenance" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
