CREATE TABLE "gebruikers" (
  "id" INT IDENTITY PRIMARY KEY,
  "voornaam" VARCHAR,
  "achternaam" VARCHAR,
  "email" VARCHAR,
  "abonnementstype" VARCHAR,
  "registratie_datum" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE "stations" (
  "id" INT IDENTITY PRIMARY KEY,
  "naam" VARCHAR,
  "straat" VARCHAR,
  "postcode" VARCHAR,
  "capaciteit" INT,
  "free_slots" INT,
  "parked_bikes" INT,
  "status" VARCHAR
);

CREATE TABLE "fietsen" (
  "id" INT IDENTITY PRIMARY KEY,
  "type" VARCHAR,
  "status" VARCHAR,
  "station_id" INT,
);

CREATE TABLE "geschiedenis" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "bike_id" INT,
  "start_station_id" INT,
  "eind_station_id" INT,
  "starttijd" TIMESTAMP WITHOUT TIME ZONE,
  "eindtijd" TIMESTAMP WITHOUT TIME ZONE,
  "minuten" INT
);

CREATE TABLE "maintenance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bike_id" INT,
  "datum" TIMESTAMP WITHOUT TIME ZONE,
  "beschrijving" TEXT,
  "status" VARCHAR
);

ALTER TABLE "rentals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("start_station_id") REFERENCES "stations" ("id");
ALTER TABLE "rentals" ADD FOREIGN KEY ("eind_station_id") REFERENCES "stations" ("id");

ALTER TABLE "bike_locations" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
ALTER TABLE "bike_locations" ADD FOREIGN KEY ("station_id") REFERENCES "stations" ("id");

ALTER TABLE "maintenance" ADD FOREIGN KEY ("bike_id") REFERENCES "bikes" ("id");
